services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  gateway:
    image: tron-the-successor/gateway
    build:
      context: services/gateway
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      FILES_SERVICE_URL: "http://files:8001"
      GAME_SERVICE_URL: "http://game:8003"
      USER_SERVICE_URL: "http://user:8004"
      CHAT_SERVICE_URL: "http://chat:8006"
  files:
    image: tron-the-successor/files
    build:
      context: services/files
    restart: unless-stopped
  game:
    image: tron-the-successor/game
    build:
      context: services/game
    restart: unless-stopped
  user:
    image: tron-the-successor/user
    build:
      context: services/user
    restart: unless-stopped
    depends_on:
      - mongodb
  chat:
    image: tron-the-successor/chat
    build:
      context: services/chat
    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongo-data:
