services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  gateway:
    image: tron-the-successor/gateway
    build:
      context: services/gateway
    ports:
      - "8000:8000"
      - "443:8443"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./ssl:/ssl
  files:
    image: tron-the-successor/files
    build:
      context: services/files
    restart: unless-stopped
  game:
    image: tron-the-successor/game
    build:
      context: services/game
    restart: unless-stopped
    env_file: .env
  user:
    image: tron-the-successor/user
    build:
      context: services/user
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongodb
  chat:
    image: tron-the-successor/chat
    build:
      context: services/chat
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongodb
  inventory:
    image: tron-the-successor/inventory
    build:
      context: services/inventory
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongodb
  notification:
    image: tron-the-successor/notification
    build:
      context: services/notification
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongodb

volumes:
  mongo-data:
