services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
  gateway:
    image: tron-the-successor/gateway
    build:
      context: services/gateway
    ports:
      - "8000:8000"
      - "8002:8002"
    restart: unless-stopped
    environment:
      FILES_SERVICE_URL: "http://files:8001"
      GAME_SERVICE_URL: "http://game:8003"
      USER_SERVICE_URL: "http://user:8004"
  files:
    image: tron-the-successor/files
    build:
      context: services/files
    restart: unless-stopped
  game:
    image: tron-the-successor/game
    build:
      context: services/game
    restart: unless-stopped
  user:
    image: tron-the-successor/user
    build:
      context: services/user
    restart: unless-stopped
    depends_on:
      - mongodb

